### ISSUE TITLE
"Oops! Something went wrong. Please try again or contact an administrator."

### ISSUE THREAD

**Issue by suckerfish** [Wizarrrr/wizarr#1]
Spun up a new Plex account under a secondary email address I have in order to try this. 

When I try to use Wizarr and punch in that email, I get the message above. 

My compose file is as follows with sensitive details adjusted. I'm behind Nginx Proxy Manager and the admin portal section works just fine in order to generate the invite codes:

```
version: "2.3"
services:
  wizarr:
    container_name: wizarr
    image: wizarr/wizarr
#    ports:
#    - 5690:5690
    networks:
      default_docker:
        ipv4_address: 172.18.0.56
    volumes:
      - ./data:/data/database
    environment:
      - "ADMIN_USERNAME=admin"
      - "ADMIN_PASSWORD=mypass"
      - "OVERSEERR_URL=https://plexrequest.mydomain.com"
      - "PLEX_NAME=Myplex"
      - "PLEX_URL=https://plex.mydomain.com/"
      - "PLEX_TOKEN=mytokenhere"
      - "APP_URL=https://wizarr.mydomain.com"
networks:
  default_docker:
    name: my_network
    ipam:
      config:
	- subnet: 172.18.0.0/16
          gateway: 172.18.0.1
```
