### ISSUE TITLE
[HELP] Authelia SSO not bypassing /setup after plex oauth

### ISSUE THREAD

**Issue by ethanopp** [Wizarrrr/wizarr#128]
Authelia SSO not working with the following conf shared in the guide:
https://docs.wizarr.dev/using-wizarr/single-sign-on-sso
```yml
access_control:
  default_policy: deny
  rules:
    - domain: "wizarr.domain.com"
      policy: bypass
      resources:
        - "^/join/"
        - "^/j/"
        - "^/setup/*"
        - "^/static/"
```

User is able to get to the "You've been invited to join the X server!" page, can click join, plex oauth comes up, but when redirected back to /setup on wizarr, getting authelia login

```yml
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr
    user: ${PUID:?err}:${PGID:?err}
    volumes:
      - ${APPDATA_DIR:?err}/Wizarr:/data/database
    environment:
      - APP_URL=https://wizarr.${DOMAIN}
      - DISABLE_BUILTIN_AUTH=true #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=${TIMEZONE}
    networks:
      container_network:
    healthcheck:
      <<: *healthchecksio
      test: ${HEALTHCHECK_WGET}/wizarr || exit 1
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - swag=enable
      - swag_auth=authelia
```

**Comment by AstralDestiny** [comment]
```yml
    - domain: wizarr.domain.com
      resources:
        - '^/join/.*$'
        - '^/j/.*$'
        - '^/static/.*$'
      policy: bypass

    - domain: wizarr.domain.com
      subject: # Part of the setup I'm not sure why wizarr says to include the setup path as a bypass. Just have the rest of it locked behind admin group in this example. Make sure the bypass rule is before the admin (this part) else it'll match this one before the bypass. 
        - 'group:administrators'
      policy: two_factor

**Comment by AstralDestiny** [comment]
That should work for you.

**Comment by ethanopp** [comment]
Still not working - redirecting me to `https://wizarr.domain.com/authelia/?rd=https%3A%2F%2Fwizarr.domain.com%2Fjoin` and showing authelia login

**Comment by ethanopp** [comment]
Following is showing in logs
`time="2023-05-13T14:33:20-04:00" level=info msg="Access to https://wizarr.xxxx.com/join (method POST) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=xxx.xxx.xx.xx
`

**Comment by mtthidoteu** [comment]
This seems to be more of an issue with Authelia. I invite you to check up with them: https://discord.authelia.com/

**Comment by ethanopp** [comment]
I don't think it is... Got it working with the following:
`    - domain: "wizarr.domain.com"
      policy: bypass
      resources:
        - '^/join/.*$'
        - '^/j/.*$'
        - '^/static/.*$'
        - '^/setup/.*$'
        - '^/join.$*'
        - '^/J.*$'
        - '^/static.*$'
        - '^/setup.*$'
        - '^/join'
        - '^/j'
        - '^/static'
        - '^/setup'
`

**Comment by AstralDestiny** [comment]
> This seems to be more of an issue with Authelia. I invite you to check up with them: https://discord.authelia.com/

```yml
    - domain: wizarr.domain.com
      resources:
        - '^/join(/.*)?$
        - '^/j(/.*)?$'
        - '^/static/.*)?$'
        - '^/setup(/.*)?$'
      policy: bypass
      
    - domain: wizarr.domain.com
      policy: two_factor
```
For Authelia ACL should function if you want to add to a page in the end..
