### ISSUE TITLE
Wizarr V3 with Authelia not working

### ISSUE THREAD

**Issue by saschabrockel** [Wizarrrr/wizarr#272]
Hey there. I recently discovered that V3 is out and recognized my setup with Authelia isn't working anymore.

Is it no longer intended to use Wizarr with Authelia since the config is gone too?

```
    - domain: wizarr.xyz.com
      resources:
        - '^/join(/.*)?$'
        - '^/j(/.*)?$'
        - '^/static(/.*)?$'
        - '^/setup(/.*)?$'
        - '^/help(/.*)?$'
      policy: bypass
```
That is my config but it does not work anymore:
![image](https://github.com/Wizarrrr/wizarr/assets/33376463/ffd2b9f1-ae91-4fe3-aabf-19daaaaa3226)
That is what I see on the website with my NGINX reverse proxy. Locally it works fine but I cannot do anything locally with the tool of course.

I should mention that it works instantly if I'm logged in in Authelia but that shouldn't be the case. I guess there is just one or more resources that need to be bypassed.
