### ISSUE TITLE
[BUG] JS error on Fresh install

### ISSUE THREAD

**Issue by Chewbaka69** [Wizarrrr/wizarr#280]
### Describe the bug:
After a fresh install on docker, when i go the url, i have a white page and a JS error.
I trie on different browser: Firefox, Opera, Edge
And in private mode but same issue

### Version used:
ghcr.io/wizarrrr/wizarr:v3-beta
ghcr.io/wizarrrr/wizarr:latest

my docker compose:
```yaml
version: "3.5"
services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:v3-beta
    #ports:
    #  - 5690:5690
    volumes:
      - /docker/volume/wizarr/database:/data/database
    restart: unless-stopped
    networks:
      compose_local:
        ipv4_address: 172.18.1.27

networks:
  compose_local:
    external:
      name: compose_br0
```

### Screenshot:
![image](https://github.com/Wizarrrr/wizarr/assets/3535011/1111deaf-8c5c-4511-b928-034876456420)
