### ISSUE TITLE
Oops! That email does not match any Plex account. Please try again.

### ISSUE THREAD

**Issue by ZuberousMaximus** [Wizarrrr/wizarr#3]
Created a new account to test out the end to end process and ran into this error on joining in with a unique code

Behind a reverse NGINX proxy here's my compose:

```
version: "3.8"
services:
  wizarr:
    container_name: wizarr
    image: wizarr/wizarr
    ports: 
    - 5690:5690
    volumes:
      - ./data:/data/database
    environment:
      - "ADMIN_USERNAME=Admin"
      - "ADMIN_PASSWORD=Password"
      - "OVERSEERR_URL= http://192.168.0.119:5055"
      - "PLEX_NAME=Plex Server Name"
      - "PLEX_URL=http://192.168.0.119:32400"
      - "PLEX_TOKEN=XXXXXXXXXXXXXXX"
      - "PLEX_SECTIONS=Movies,TV Shows" # Important: Make sure to not leave any unnecessary spaces
      - "APP_URL=https://www.website.com/invite"
```

Docker Logs:

```
wizarr | [2022-09-13 07:24:32 +0000] [1] [INFO] Starting gunicorn 20.1.0

wizarr | [2022-09-13 07:24:32 +0000] [1] [INFO] Listening at: http://0.0.0.0:5690 (1)

wizarr | [2022-09-13 07:24:32 +0000] [1] [INFO] Using worker: sync

wizarr | [2022-09-13 07:24:32 +0000] [7] [INFO] Booting worker with pid: 7

wizarr | [2022-09-13 07:24:32 +0000] [8] [INFO] Booting worker with pid: 8

wizarr | [2022-09-13 07:24:32 +0000] [9] [INFO] Booting worker with pid: 9

wizarr | ERROR:root:Unable to find user: Email Address`

```
