### ISSUE TITLE
Latest version doesn't work with Traefik

### ISSUE THREAD

**Issue by daurpam** [Wizarrrr/wizarr#301]
I was using traefik as reverse proxy, and it was working until version 3.4.8. 
I've test inside wizarr docker container a curl http://localhost:5690 succesfully. But outside the container through the proxy it doesn't respond.

I've check the tags and commands inside the different versions and seems that some commands are different including the command related with the port exposition:
```EXPOSE map[5690/tcp:{}]```  <-- appears in tag: latest-3.4.2 but not in 3.4.8 or latest

Perhaps could be the reason of the issue?

Thanks for your work.

**Comment by realashleybailey** [comment]
Could you share relevant configs, like Docker Compose, Traefik config, and what Docker networks there both on

**Comment by daurpam** [comment]
These are my docker-compose files for:
* Traefik
```
version: '3.4'

services:
  proxy:
    image: traefik:latest
    container_name: proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "2222:2222"
#      - "9080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./conf:/etc/traefik
      - ./logs:/logs
      - ./ssl:/ssl
    networks:
      - proxy

networks:
  proxy:
    external: true
```

* Wizarr
```
version: "3.8"
services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest-3.4.2
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./config:/data/database
    environment:
      - APP_URL=https://mydomain.com #URL at which you will access and share
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=Europe/Madrid #Set your timezone here
    labels:
      - traefik.enable=true
      - traefik.http.routers.cronoswiz.entrypoints=web
      - traefik.http.routers.cronoswiz.rule=Host(`mydomain.com`)
      - traefik.http.routers.cronoswiz.middlewares=redirect-https@file
      - traefik.http.routers.cronoswizs.entrypoints=secure
      - traefik.http.routers.cronoswizs.rule=Host(`mydomain.com`)
      - traefik.http.routers.cronoswizs.tls.certresolver=le
      - com.centurylinklabs.watchtower.enable=true

networks:
  proxy:
    external: true
```
This version of docker-compose.yml works, if change to newest images, I got errors on traefik logs, like:
- ``` TRAEFIK: LEVEL=ERROR MSG=“FIELD NOT FOUND, NODE: PORT MISSING ``` 
if I don't setup the "..loadbalancer.server.port=5690" value inside the traefik labels or
- ``` TRAEFIK: LEVEL=ERROR MSG=“FIELD NOT FOUND, NODE: SERVER ``` 
if the previous label is setup inside docker-compose.yml 

Hope it helps. Thanks

**Comment by realashleybailey** [comment]
```
version: "3.8"
services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest-3.4.2
    restart: unless-stopped
    networks:
      - proxy
      - (your_default_docker_network)
    volumes:
      - ./config:/data/database
    labels:
      - traefik.enable=true
      - traefik.http.routers.cronoswiz.entrypoints=web
      - traefik.http.routers.cronoswiz.rule=Host(`mydomain.com`)
      - traefik.http.routers.cronoswiz.middlewares=redirect-https@file
      - traefik.http.routers.cronoswizs.entrypoints=secure
      - traefik.http.routers.cronoswizs.rule=Host(`mydomain.com`)
      - traefik.http.routers.cronoswizs.tls.certresolver=le
      - com.centurylinklabs.watchtower.enable=true

networks:
  proxy:
    external: true
```
