### ISSUE TITLE
Current version differs from Server, server reporting 404 page not found

### ISSUE THREAD

**Issue by didyouexpectthat** [Wizarrrr/wizarr#40]
```
wizarr    | WARNING:root:Current version differs from Server, server reporting 404 page not found
wizarr    |  but we have 0.11.0
```
![image](https://user-images.githubusercontent.com/1329077/211247415-17dad91e-6747-47a3-9b6f-71f704f4484a.png)

```
# cat docker-compose.yaml
version: "3.3"
services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr
    ports:
    - 5690:5690
    volumes:
      - /opt/wizarr/:/data/database
    environment:
      - APP_URL=https://wizarr.domain.local
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - ALLOW_BUG_REPORTING=true #Helps me fix bugs, but you can disable it if you want! I use Sentry.io for this.
```
