### ISSUE TITLE
[Bug] | Unable to select Jellyseerr with Plex Media Server Setup

### ISSUE THREAD

**Issue by iamronr** [wizarrrr/wizarr#451]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

When configuring the request portion of Wizarr, it's not allowing me to choose Jellyseerr as the app of choice, only Overseerr and Ombi, neither of which I use.

### Virtualisation

Docker

### What operating system are you seeing the problem on?

macOS

### What browsers are you seeing the problem on?

Safari

### Project Location

Local

### Bug Description

When configuring the request portion of Wizarr, it's not allowing me to choose Jellyseerr as the app of choice, only Overseerr and Ombi, neither of which I use.

### Steps to Reproduce

Go to add request service, and when I click on actual service, Jellyseerr is greyed out.

![TRC](https://github.com/wizarrrr/wizarr/assets/698319/1b3b7f63-7e44-40cf-a94d-40a315f9dfbf)

**Comment by JamsRepos** [comment]
You are only allowed to select Jellyseerr once your media server is properly configured. Please ensure you have verified the connection, selected libraries and then saved the connection.

**Comment by iamronr** [comment]
I did exactly that, and tried again, and the options are still the same.

![TRC](https://github.com/wizarrrr/wizarr/assets/698319/76aeb0c2-cc5d-4f4e-8d46-93bebbf6bcef)

**Comment by JamsRepos** [comment]
That says verified bottom right, click the same button again which says save to save it.

**Comment by iamronr** [comment]
I did click it twice, it showed saved. It's still oddly not allowing me to choose.

**Comment by iamronr** [comment]
Here's what I have in my docker-compose. I'm not sure if the `JELLYFIN_TYPE=plex` is the cause of it...

```
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file: server.env
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=debug
      - JELLYFIN_TYPE=plex
    ports:
      - 5055:5055
    volumes:
      - $SERVER/jellyseerr:/app/config
      - $SERVER/jellyseerr/logos/logo_full.png:/app/public/logo_full.png
      - $SERVER/jellyseerr/logos/logo_full.svg:/app/public/logo_full.svg
      - $SERVER/jellyseerr/logos/logo_stacked.svg:/app/public/logo_stacked.svg
      - $SERVER/jellyseerr/logos/os_logo_square.png:/app/public/os_logo_square.png
    restart: unless-stopped
```
