### ISSUE TITLE
[HELP] Reverse proxy configuration not working after update to 2025.05

### ISSUE THREAD

**Issue by jenssvedlund** [wizarrrr/wizarr#535]
**Describe the bug**
After upgrade to 2025.05 wizarr is no longer reachable over the nginx reverse proxy.
When browsed on the  LAN IP address it works fine. When browsed over the reverse proxy, I'm just greeted with a white blank screen. This setup was working prior to updating.

**Logs**
```
2025-05-23 20:37:31,304  INFO      404: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Additional context**
Docker Compose file
```                                                                                                                
services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    restart: unless-stopped
    environment:
      - APP_URL=https://<public URL>
      - DISABLE_BUILTIN_AUTH=false
      - TZ=Europe/London
    ports:
      - 5690:5690
    volumes:
      - /mnt/hdd/wizarr/database:/data/database
      - /mnt/hdd/wizarr/wizard:/data/wizard_steps
```
Nginx Config
```                                                                                                                
server {
        server_name <public URL>;
        proxy_set_header Referer $http_referer;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-Port $remote_port;
        proxy_set_header X-Forwarded-Host $host:$remote_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Port $remote_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl on;
        location / {
                proxy_pass http://192.168.20.11:5690;
        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/<public URL>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<public URL>privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = <public URL>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        server_name <public URL>;
    listen 80;
    return 404; # managed by Certbot


}

```
