### ISSUE TITLE
[BUG] Failed to connect to the backend -private.key no such file or directory

### ISSUE THREAD

**Issue by begunfx** [wizarrrr/wizarr#540]
**Describe the bug**
Docker compose builds successfully, but when I try to access the UI on: host:5690 I get failed to connect to the backend.  In the portainer log I see that it can't fine the private.key file

**Screenshots**

**Logs**
If applicable, add logs to help explain your problem
```
                   ^
Error: ENOENT: no such file or directory, open '/volume1/docker/wizarr/data/storage/private.key'
    at writeFileSync (node:fs:2344:20)
    at RsaKeyPairGenJob.<anonymous> (/usr/wizarr/apps/server/src/utils/secret.helper.js:38:36)
    at job.ondone (node:internal/crypto/keygen:93:5) {

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/volume1/docker/wizarr/data/storage/private.key'
}
Node.js v22.12.0
Running Wizarr Backend in production mode
 WARN  Environment file not found. Using default environment variables.

node:fs:2344
    return binding.writeFileUtf8(
```

**Additional context**
Here's a copy of my compose file:
```
services:
    wizarr-nginx:
        container_name: wizarr_nginx
        restart: on-failure
        image: nginx:1.24.0-alpine
        depends_on:
            wizarr-frontend:
                condition: service_started
            wizarr-backend:
                condition: service_started
        ports:
            - ${PORT:-5690}:5690
        environment:
            - PORT=5690
            - FRONT_URL=http://wizarr-frontend:5173
            - SERVER_URL=http://wizarr-backend:5001
        volumes:
            - /volume1/docker/wizarr/nginx/nginx.conf.template:/etc/nginx/templates/wizarr.conf.template:ro

    wizarr-frontend:
        container_name: wizarr_frontend
        image: ghcr.io/wizarrrrr/wizarr-frontend:${WIZARR_IMAGE_VERSION:-latest}
        restart: always

    wizarr-backend:
        container_name: wizarr_backend
        image: ghcr.io/wizarrrrr/wizarr-backend:${WIZARR_IMAGE_VERSION:-latest}
        volumes:
            # Do not edit the next line. If you want to change the storage location on your system, edit the value of STORAGE_DIR in the .env file
            - ${DB_DIR}:/usr/wizarr/data/database
            - ${STORAGE_DIR}:/usr/wizarr/data/storage
            - /etc/localtime:/etc/localtime:ro
        env_file:
            - stack.env
        depends_on:
            - redis
            - postgres
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
            interval: 30s
            timeout: 10s
            retries: 5

    redis:
        container_name: wizarr_redis
        image: docker.io/redis:latest
        healthcheck:
            test: redis-cli ping || exit 1
        restart: always

    postgres:
        container_name: wizarr_postgres
        image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DIR}
            POSTGRES_INITDB_ARGS: "--data-checksums"
        volumes:
            # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DIR in the .env file
            - ${DB_DIR}:/var/lib/postgresql/data
        command: >-
            postgres
            -c shared_preload_libraries=vectors.so
            -c 'search_path="$$user", public, vectors'
            -c logging_collector=on
            -c max_wal_size=2GB
            -c shared_buffers=512MB
            -c wal_compression=on
        restart: always

    memcached:
        container_name: wizarr_memcached
        restart: always
        image: "memcached:alpine"
        command:
            - --conn-limit=1024
            - --memory-limit=64
            - --threads=4
        healthcheck:
            test: echo stats | nc 127.0.0.1 11211
            interval: 20s
            timeout: 1s
            retries: 5

    s3:
        container_name: wizarr_s3
        restart: always
        image: zenko/cloudserver:latest
        environment:
            S3METADATAPATH: /var/lib/s3/meta
            S3DATAPATH: /var/lib/s3/data
            REMOTE_MANAGEMENT_DISABLE: true
            HOST_NAMES: "s3"
        volumes:
            - ${STORAGE_DIR}/meta:/var/lib/s3/meta
            - ${STORAGE_DIR}/data:/var/lib/s3/data
```
