### ISSUE TITLE
Run docker container without root

### ISSUE THREAD

**Issue by drkno** [wizarrrr/wizarr#545]
It is currently not easy to run the container without running the container as root. Running without root is desirable to provide a bit more isolation and reduce the attack surface if something goes wrong. It's also useful in more locked down environments where running as root isn't available.

Ideally this would be as trivial as setting a user in the docker compose, but setting the user there fails in a few different ways:

* `cp -a` in [`docker-entrypoint.sh`](https://github.com/wizarrrr/wizarr/blob/main/docker-entrypoint.sh#L16) attempts to copy with permissions, which fails if not running as root because permissions can't be set
* `/.cache` needs to be writable, but is owned by root

These can be worked around like this (but ideally wouldn't require workarounds):

1. ```shell
    # The following are based on the configs from the install instructions
    mkdir -p config/wizarr/database
    mkdir config/wizarr/wizard

    # This one is required because "uv" expects the cache directory to be writable
    # Will be volume mounted to /.cache
    mkdir config/wizarr/cache
    ```

2. `cp -a` in [`docker-entrypoint.sh`](https://github.com/wizarrrr/wizarr/blob/main/docker-entrypoint.sh#L16) attempts to copy with permissions, which fails if not running as root. Manually execute those steps.
    ```shell
    docker run --rm -it \
        --entrypoint /bin/cp \
        -v ./config/wizarr/database:/data/database \
        -v ./config/wizarr/wizard:/data/wizard_steps \
        ghcr.io/wizarrrr/wizarr \
        '/opt/default_wizard_steps/*' '/data/wizard_steps/'
    ```

3. Make sure the config directories are owned by the correct user
    ```shell
    sudo chown -R $WIZARR_USER:$WIZARR_GROUP config/wizarr
    ```

4. Run the container
    ```yaml
    services:
        wizarr:
            container_name: wizarr
            image: ghcr.io/wizarrrr/wizarr:latest
            restart: unless-stopped
            environment:
                - TZ=${TZ}
                - APP_URL=${WIZARR_APP_URL}
            volumes:
                - /etc/localtime:/etc/localtime:ro
                - ./config/wizarr/database:/data/database
                - ./config/wizarr/wizard:/data/wizard_steps
                - ./config/wizarr/cache:/.cache
            user: "${WIZARR_USER}:${WIZARR_GROUP}"
            stop_grace_period: 120s
    ```

**Comment by peterbuga** [comment]
a quick solution that worked for me 

```
volumes:
  - type: "tmpfs"
    target: "/.cache"
    tmpfs:
      mode: 0777
```

```
du -hs /.cache/
48.0K	/.cache/
```
