### ISSUE TITLE
[BUG] `/.cache/uv`: Permission denied - 2025.6.1

### ISSUE THREAD

**Issue by Toomblr** [wizarrrr/wizarr#590]
**Describe the bug**
Since 2025.6.1, the container won't start anymore

**Logs**
```
wizarr exited with code 2
wizarr  | [entrypoint] skipping wizard-steps seed (already populated)
wizarr  | [entrypoint] 🔄 Renaming legacy database (if any)…
wizarr  | error: failed to create directory `/.cache/uv`: Permission denied (os error 13)
wizarr exited with code 2
wizarr  | error: failed to create directory `/.cache/uv`: Permission denied (os error 13) 
```

**Docker compose**
```
services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    #    ports:
    #      - 5690:5690
    volumes:
      - /mnt/ssd0/docker/data/wizarr/database:/data/database
      - /mnt/ssd0/docker/data/wizarr/wizard:/data/wizard_steps
    environment:
      - APP_URL=https://wizarr.MYDOMAIN.nl #URL at which you will access and share 
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=Europe/Amsterdam #Set your timezone here
    restart: unless-stopped
    networks:
      - npm
    user: 568:568
networks:
  npm:
    external: true
```
