### ISSUE TITLE
[BUG] Container no longer starts, permission denied to create a folder

### ISSUE THREAD

**Issue by spcrepeau** [wizarrrr/wizarr#645]
Container won't start in docker (Synology). Error: mkdir: can't create directory '/data/wizard_steps/audiobookshelf': Permission denied. All files/folder in the wizarr folders are owned by the UID/GIDs set in the containers environment.

It was working a few weeks ago after the PUID and PGID fix.

**Comment by spcrepeau** [comment]
Compose setup:
```yaml  
  wizarr:
    image: ghcr.io/wizarrrr/wizarr:latest
    container_name: wizarr
    environment:
      PGID: ${DOCKER_GID}
      PUID: ${DOCKER_UID}
      TZ: ${TZ}
      DISABLE_BUILTIN_AUTH: false
    ports:
      - ${WIZARR_PORT_5690}:5690 # Web GUI HTTP
    volumes:
      - ./wizarr/database:/data/database
      - ./wizarr/wizard:/data/wizard_steps
    network_mode: bridge
    security_opt: ['no-new-privileges:true']
    restart: unless-stopped
```
