### ISSUE TITLE
[BUG] Python `No module named 'app'` on Docker Compose Start

### ISSUE THREAD

**Issue by arch1eOS** [wizarrrr/wizarr#653]
# [BUG] Python `No module named 'app'` on Docker Compose Start

<a name="overview"></a>
> Hello all, I am currently unable to start a wizarr container through docker compose, with starting the containers straight after showing that wizarr was not running. I have traced this error to python complaining about not finding the module `app` from `app.legacy_migration.rename_legacy` when trying to `🔄 Renaming legacy database (if any)…`.

### Logs
```
wizarr  | [entrypoint] 🚀 Starting Wizarr container…
wizarr  | [entrypoint] 👤 Wanted UID=1000  GID=1000
wizarr  | [entrypoint] ⚙️  Fixing ownership for bind mounts…
wizarr  | [entrypoint] ⚙️  Default UID/GID; skipping chown.
wizarr  | [entrypoint] 🚀 Starting Wizarr container…
wizarr  | [entrypoint] 👍 Running as wizarruser:wizarrgroup (1000:1000)
wizarr  | [entrypoint] ↩️  Custom wizard steps for audiobookshelf detected – keeping user files
wizarr  | [entrypoint] ↩️  Custom wizard steps for emby detected – keeping user files
wizarr  | [entrypoint] ↩️  Custom wizard steps for jellyfin detected – keeping user files
wizarr  | [entrypoint] ↩️  Custom wizard steps for plex detected – keeping user files
wizarr  | [entrypoint] 🔄 Renaming legacy database (if any)…
wizarr  | /usr/local/bin/python: Error while finding module specification for 'app.legacy_migration.rename_legacy' (ModuleNotFoundError: No module named 'app')
```
### Behavior

- [Running `docker compose up -d` after already starting it shows wizarr as started instead of running](#overview)
- This happens in relatively quick succession.
- [Running 'docker compose logs -f wizarr' shows wizarr failing with a module not found after trying to rename a legacy database.](#logs)

## Relevant Info
- OS: Alpine Linux LXC inside Proxmox
### Docker Compose File
```
services:
...
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:dev
    ports:
      - 5690:5690
    restart: unless-stopped
    volumes:
      - /containers/media/wizarr:/data
      # - /path/to/appdata/config/database:/data/database
      # - /path/to/appdata/config/wizard:/data/wizard_steps
    environment:
      - PUID=1000 #Set UID
      - PGID=1000 #Set GID
      - DISABLE_BUILTIN_AUTH=true #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=Australia/Melbourne #Set your timezone
...
```
## Recreation

1. Have docker and compose installed.
2. Create a `compose.yaml` containing [wizarr's docker compose instructions](https://docs.wizarr.dev/getting-started/installation#tab-docker-compose-recommended).
3. Append `dev`, `latest`, `2025.6.3b` or `2025.6.3` to the docker image.
4. Save and run `docker compose up -d`.
5. Observe.

## Attempted fixes

- Changed version to `dev`, `latest`, `2025.6.3b` or `2025.6.3`. 
> [!NOTE]
> Anything '2025.6.3'> perceivably removes the issue however throws #603 
- Removing and reinstalling, updating, etc.
- Changed volume binds
- Toggle commented env variables
